config/routes.rb
Rails.application.routes.draw do

    root 'home#dashboard'

    get '/new_role' , to: 'home#new_role'
    get '/roles_list' , to: 'home#roles_list'
    post '/create_role' , to: 'home#create_role'
    post '/manage_roles' , to: 'home#manage_roles'

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def dashboard
   @roles =  Role.all.order(role_name: :asc)
  end

  def new_role
    @role = Role.new
    respond_to do |format|
      format.js
    end
  end

  def create_role
    @role =  Role.create(role_params)
    respond_to do |format|
      format.js
    end
  end

  def roles_list
    @roles =  Role.all.order(role_name: :asc)
  end

  def manage_roles
if params[:role].present?
   @roles = Role.where(id: params[:role])
   if params[:act_typ] == "Active"
   @roles.update_all(role_status: true)
   else
     @roles.update_all(role_status: false)
   end
   end
   respond_to do |format|
     format.js
   end
  end


  private

  def role_params
    params.require(:role).permit(:role_name,:role_status)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_active_roles.html.erb
<table class="table table-hover users-table" id="all_request_table">
  <thead>
  <tr>
    <th class="logo_sorting">Role</th>
    <th class="company__name">Status</th>
  </tr>
  </thead>
  <tbody>
  <% @roles.each do |role|%>
      <tr>
        <td class="role">
          <%= role.role_name%>
        </td>
        <td class="status"><%= role.role_status%></td>
      </tr>
  <%end%>
  </tbody>
</table>

app/views/home/_create_role.html.erb
<div class="modal-dialog modal-sm" role="document" style="width: 918px;">
  <%= form_for @role, url: create_role_path , remote: true do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add New Role</h4>
        </div>
        <div class="clearfix"></div>
        <div class="modal-body">
          <div class="clearfix"></div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :role_name ,class: "form-control"%>
              <%= f.hidden_field :role_status,value: true %>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="modal-footer">
          <span class="uniq_msg unique_error"  style="display: none;font-size: 13px; font-weight: normal; color: red; margin-left: 18px">Company Name with this email already exists do you still want to continue</span>

          <span class="uniq_msg" id="email_uniq" style="display: none;font-size: 13px; font-weight: normal; color: red; margin-left: 18px">Company Name with this email already exists do you still want to continue</span>
          <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          <%= f.submit "Save", class: "btn btn-primary validation_btn"%>
        </div>

      </div>
  <%end%>
</div>

app/views/home/_manage_roles.html.erb
<div class="modal-dialog" role="document" style="width: 918px;">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add New Role</h4>
        </div>
        <div class="clearfix"></div>
        <div class="modal-body">

<table class="table table-hover users-table" id="all_request_table">
  <thead>
  <tr>
    <th class="check"><input id="checkBox" type="checkbox" class="toggleAll"></th>
    <th class="logo_sorting">Role</th>
    <th class="company__name">Status</th>
  </tr>
  </thead>
  <tbody>
  <% @roles.each do |role|%>
      <tr>
        <td>
          <input class="checkbox" type="checkbox">
        </td>
        <td class="role">
          <%= role.role_name%>
          <%= hidden_field_tag :role_id, role.id,class: "role_id"%>
        </td>
        <td class="status"><%= role.role_status%></td>
      </tr>
  <%end%>
  </tbody>
</table>

          <div class="clearfix"></div>
          <div class="modal-footer">
            <%= submit_tag "Active",value: "Active" ,class: "btn btn-success active_roles btn_active_request "%>
            <%= submit_tag "Inactive",value: "Inactive" ,class: "btn btn-primary btn_inactive_request"%>
          </div>

        </div>
  </div>
  </div>

<script>
        (function($){
            $('.btn_active_request, .btn_inactive_request').on('click', function(e) {
                e.preventDefault();
                var action_type = $('.btn_active_request').val();
                var request = [];
                if ($(this).hasClass('active_roles')){
                    var act_typ = "Active"
                } else {
                    var act_typ = "Inactive"
                }

                $("#all_request_table td:first-child input.checkbox:checked").each(function() {
                    var $row = $(this).parents("tr").first();
                    request.push( $row.find(".role_id").val() )
                });

                $.ajax({
                    type: "POST",
                    url: "/manage_roles",
                    data: {role: request,act_typ: act_typ},
                    success: function() {
                    }
                });
                console.log('Request IDs', request);
            });

        $(".toggleAll").on("change", function() {
            var isChecked = $(this).prop("checked");

            var $table = $(this).parents("table");
            $table.find('tbody .checkbox').prop('checked', isChecked);
        })

    })(jQuery)
</script>

app/views/home/create_role.js.erb
$('#addRole').modal('hide');

app/views/home/dashboard.html.erb
<div class="container">

  <div class="well">

   <%= link_to "Add Roles", new_role_path ,data: {toggle: "modal", id: "addRole",target: "#addRole"} ,:remote => true,class: "btn btn-primary addRole" %>
   <%= link_to "Hide Roles", roles_list_path ,data: {toggle: "modal", id: "manageRole",target: "#manageRole"} ,:remote => true,class: "btn btn-primary manageRole" %>
  <%= button_tag "User Management" ,class: "btn btn-primary"%>
  </div>
</div>

<div class="modal fade" id="addRole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<div class="modal fade" id="manageRole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<!--<div class="container">-->

  <!--<div class="well active_roles">-->
    <!--<%#= render "active_roles"%>-->
  <!--</div>-->
<!--</div>-->

app/views/home/manage_roles.js.erb
$('#manageRole').modal('hide');
$(".active_roles").html("<%= escape_javascript(render 'active_roles') %>");

app/views/home/new_role.js.erb
$("#addRole").html("<%= escape_javascript(render 'create_role') %>");

app/views/home/roles_list.js.erb
$("#manageRole").html("<%= escape_javascript(render 'manage_roles') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lotvue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>